import Head from 'next/head'
import { NextPage } from 'next'
import { IRoom } from '@/shared/schemas'
import { Home } from '@/components/Pages'
import { CardProps } from '@/components/Organisms'
import { Layout } from '@/components/Templates'
import { roomCardMapper } from '@/containers/helpers/home.mapper'

export type HomeContainerStateType = {
  isLoading: boolean
  error?: string
  rooms: IRoom[]
}
// export type HomeContainerDispatchType = {
//   setRoomsAction: typeof setRoomsAction
// }
type HomeContainerType = HomeContainerStateType

const HomeContainer: NextPage<HomeContainerType> = ({ isLoading, rooms = [] }) => {
  let cardListProps: CardProps[] = []

  if (!isLoading) {
    cardListProps = rooms.map(roomCardMapper)
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Layout>{isLoading ? <div>is loading ...</div> : <Home cardList={cardListProps} />}</Layout>
      </main>

      <footer></footer>
    </div>
  )
}

export default HomeContainer
