import Head from 'next/head'
import { NextPage } from 'next'
import { IRoom } from '@/shared/schemas'

export type HomeContainerStateType = {
  isLoading: boolean
  error?: string
  rooms: IRoom[]
}
// export type HomeContainerDispatchType = {
//   setRoomsAction: typeof setRoomsAction
// }
type HomeContainerType = HomeContainerStateType

const HomeContainer: NextPage<HomeContainerType> = ({ isLoading, rooms }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Welcome to Booking project </h1>
      </main>

      {!isLoading && JSON.stringify(rooms, null, 2)}

      <footer></footer>
    </div>
  )
}

export default HomeContainer
