name: Deploy NextJs with Vercel Production

on: workflow_dispatch

# Allow one concurrent deployment
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-production:
    environment:
      name: Production
      url: https://booking-prod.vercel.app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Github env vars to Vercel
      # https://github.com/dkershner6/vercel-set-env-action
      - name: Set Github Env Vars (production) on Vercel Production Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: booking # project name in Vercel
          envVariableKeys: DB_URI
        env:
          DB_URI: ${{ secrets.DB_URI }}
          TARGET_DB_URI: production # vercel environment: comma delimited, one of [production, preview, development]
          TYPE_DB_URI: encrypted # one of [plain, encrypted]

      # deploy app to vercel
      # https://github.com/amondnet/vercel-action
      - name: deploy site to vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required

